# Generated by Django 4.2.4 on 2023-08-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
