# Generated by Django 4.2.4 on 2023-08-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_works_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phonenum', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
