# Generated by Django 4.2.4 on 2023-08-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_details_userid_alter_details_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='userid',
            new_name='username',
        ),
    ]
