# Generated by Django 4.2.4 on 2023-08-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_userid_details_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='IntId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
