# Generated by Django 4.2.4 on 2023-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_works_intid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('strength', models.IntegerField()),
                ('menWage', models.IntegerField()),
                ('womenWage', models.IntegerField()),
                ('phonenum', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
