# Generated by Django 4.2.4 on 2023-08-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_postjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobs',
            name='name',
            field=models.CharField(default='Damin Risho', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postjobs',
            name='username',
            field=models.CharField(default='daminrisho', max_length=500),
            preserve_default=False,
        ),
    ]
