# Generated by Django 4.2.4 on 2023-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_postjobs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjobs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
