# Generated by Django 4.2.4 on 2023-08-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_postjobs_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostJobs',
        ),
    ]
