# Generated by Django 4.2.4 on 2023-08-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_postjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobs',
            name='strId',
            field=models.CharField(default='null', max_length=10000),
            preserve_default=False,
        ),
    ]
